#-------------
# Bexxkie
# 01-may-2019
# ver 2.0
# QIcoGen
#------------
#
# NOTE: this overwrites existing desktop.ini
#
from PIL import Image
import sys
from configparser import RawConfigParser
import ctypes
import os
#-- Vars
f = sys.argv[1]					# this will get the dragged file, (if it is not an image, it just closes)
i = Image.open(f)				# go ahead and load it as an image (otherwise just close like said above)
name = f.split('.')[0]+'.ico'	# wanna split get the filename and get index 0, so like 001.jpg => [001],[jpg]
ico = i.save(name)				# convert and save the file to the same folder the the dragged image came from
dir = os.path.dirname(f)
#-- Desktop.ini generator
config = RawConfigParser()
config.optionxform=str
cfFile = open(dir+'\\desktop.ini','w')

# Create the ini sections we want [.ShellClassInfo], [ViewState]
config.add_section('.ShellClassInfo')
config.add_section('ViewState')

# Icon Path, autogenerated from the source of the dragged object
config.set('.ShellClassInfo','IconResource',name+',0')
# Folder type, should be Video, Generic, Pictures
config.set('ViewState','FolderType','Generic')
# write the file to disk (save)
config.write(cfFile)
# close the stream
cfFile.close()
# get the dir, not the file
os.chdir(dir)
# set the dir's attributes so windows will use the ini properly
os.system('attrib +S +H desktop.ini')
#
# :Optionals: uncomment to use
# Alerts user when completed (this wont show if the script fails in any way)
#ctypes.windll.user32.MessageBoxW(0, "Icon created and applied to folder", "Done", 1)


#--------
# Extra Information

# This is what the INI should look like, if it doesnt then change the
#[.ShellClassInfo]
#IconResource=PATH_TO_ICO,0
#[ViewState]
#FolderType= FOLDER TYPE (Pictures, Generic, Video)



# Use if thumbnails are not updated (alternatively rebooting will work)
# Batch file assoc with this script to force thumbnails to be updated
# (run in root folder IE: create icon for Images/CuteCats, run the following script in Images)
#
#
#@echo off
#for /r %%I in (*.ico) do (
#    attrib -h -s -r "%temp%\desktop.ini" >nul
#    (
#        echo [.ShellClassInfo]
#        echo IconResource="%%~nxI",0
#    )>"%temp%\desktop.ini"
#    attrib +h +s "%temp%\desktop.ini"
#    (
#        echo set shell = CreateObject^("Shell.Application"^)
#        echo set folder = shell.NameSpace^("%%~dpI"^)
#        echo folder.MoveHere "%temp%\desktop.ini", 4+16+1024
#    )>"%temp%\updateIcon.vbs"
#    cscript //nologo //b "%temp%\updateIcon.vbs"
#)
#pause
